services:
  commafeed:
    image: athou/commafeed:4.4.0
    container_name: commafeed
    restart: unless-stopped
    environment:
      - "CF_APP_PUBLIC_URL=https://commafeed.{{ domain }}"
    volumes:
      - "{{ data_dir }}/{{ role_name }}/data:/commafeed/data"

networks:
  default:
    name: reverse-proxy
    external: true
