---
- name: Deploy all public infrastructure services
  hosts: vps
  remote_user: debian
  roles:
    - role: geerlingguy.docker
      become: yes
    - role: traefik
      tags: [ proxy ]
    - role: commafeed
      tags: [ services ]
    - role: pairdrop
    - role: diun
    - role: restic
    - role: grafana
    - role: prometheus
    - role: promtail

