---
- name: Deploy all public infrastructure services
  hosts: vps
  remote_user: debian
  roles:
    - role: geerlingguy.docker
      become: yes
    - role: reverse-proxy
    - role: commafeed
    - role: pairdrop
    - role: diun
    - role: restic

