---
- name: Deploy all public infrastructure services
  hosts: vps
  remote_user: debian
  roles:
    - role: geerlingguy.docker
      become: yes
      tags: [ dependencies ]
    - role: traefik
      tags: [ proxy ]
    - role: commafeed
      tags: [ commafeed ]
    - role: pairdrop
    - role: diun
    - role: restic
    - role: grafana
      tags: [ monitoring ]
    - role: influxdb
      tags: [ monitoring ]
    #- role: promtail
    #  tags: [ monitoring ]

