global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      # Prometheus
      - targets: ['localhost:9090']
      # nginx-prometheus-exporter
      - targets: ['nginx-prometheus-exporter:9113']

#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'
