watch:
  workers: 20
  schedule: "0 */6 * * *"
  firstCheckNotif: false

providers:
  docker:
    watchByDefault: true

notif:
  ntfy:
    endpoint: https://ntfy.sh
    topic: cSRGClqmpBIhRhOj
    priority: 3
    tags:
      - whale
    timeout: 10s
{% raw %}
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
{% endraw %}

