---
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    volumes:
      - "{{ data_dir }}/{{ role_name }}/data:/var/lib/grafana"

networks:
  default:
    name: reverse-proxy
    external: true

