---
- name: Create install directory
  file:
    path: "{{ install_directory }}/{{ role_name }}"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true

- name: Copy nginx.conf file to destination
  copy:
    src: nginx.conf
    dest: "{{ data_dir }}/{{ role_name }}/config/nginx/nginx.conf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy cloudflare.ini file to destination
  template:
    src: cloudflare.ini
    dest: "{{ data_dir }}/{{ role_name }}/config/dns-conf/cloudflare.ini"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy MaxMind GeoIP DB file to destination
  copy:
    src: GeoLite2-Country.mmdb
    dest: "{{ data_dir }}/{{ role_name }}/config/nginx/GeoLite2-Country.mmdb"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy stub_status.conf file to destination
  template:
    src: stub_status.conf
    dest: "{{ data_dir }}/{{ role_name }}/config/nginx/site-confs/stub_status.conf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy grafana.subdomain.conf file to destination
  template:
    src: grafana.subdomain.conf
    dest: "{{ data_dir }}/{{ role_name }}/config/nginx/proxy-confs/grafana.subdomain.conf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy commafeed.subdomain.conf file to destination
  template:
    src: commafeed.subdomain.conf
    dest: "{{ data_dir }}/{{ role_name }}/config/nginx/proxy-confs/commafeed.subdomain.conf"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
  become: true
  notify: Restart reverse-proxy

- name: Copy docker-compose file to destination
  template:
    src: docker-compose.yml
    dest: "{{ install_directory }}/{{ role_name }}/docker-compose.yml"
    owner: "{{ primary_user }}"
    group: "{{ primary_group }}"
    validate: docker compose -f %s config
  become: true
  notify: Restart reverse-proxy

- name: Call restart handler
  ansible.builtin.meta: flush_handlers

