- include_role: 
    name: grafana.grafana.grafana
  vars:
    grafana_address: "127.0.0.1"
    grafana_alerting: {}
    grafana_security:
      admin_user: admin
      admin_password: "{{ ADMIN_PASSWORD }}"

